apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: signals-test
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: signals-test
    spec:
      containers:
      - name: signals-test
        image: ministryofjustice/signals-test:0.3
