---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: signals-test
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: signals-test
    spec:
      containers:
      - name: signals-test
        image: ministryofjustice/signals-test:0.3
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: signals-test-pdb
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: signals-test
